spring.application.name=auth-service
server.port=8083

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/starlight_auth
spring.datasource.username=postgres
spring.datasource.password=Gowtham@123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
jwt.secret=mySecretKeyForStarlightHotelApplication123456789